name: 部署到Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 安装依赖
        run: |
          npm install
          npm install vite-plugin-pwa --save-exact
      
      - name: 显示已安装的依赖
        run: |
          echo "已安装的依赖:"
          npm list vite-plugin-pwa
      
      - name: 运行构建脚本
        run: npm run build
      
      - name: 检查构建输出
        run: |
          echo "构建目录内容:"
          ls -la dist/
      
      - name: 验证Cloudflare账户ID格式
        run: |
          # 验证账户ID格式
          if [[ "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" =~ ^[a-f0-9]{32}$ ]]; then
            echo "账户ID格式正确"
          else
            echo "警告：账户ID格式可能不正确，请确认是否为32位十六进制字符"
          fi
      
      - name: 部署到Cloudflare Pages
        id: deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: freepdftools
          directory: dist
        env:
          DEBUG: "true"
      
      - name: 部署结果
        if: always()
        run: |
          echo "部署状态: ${{ steps.deployment.outcome }}"
          echo "如果部署失败，请检查Cloudflare API令牌和账户ID是否正确"